[[pages]]
path = "pages/agent.py"
name = "Chat with IVY Moda"
icon = "ğŸ›ï¸"
url_path = "."

[[pages]]
path = "pages/about.py"
name = "About Us"
icon = "ğŸ‘‹"
url_path = "about"

[[pages]]
path = "pages/guide.py"
name = "User Guide"
icon = "ğŸ“•"
url_path = "guide"
